apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-manager-sa
  namespace: airflow
  annotations:
    eks.amazonaws.com/role-arn: <aws-iam-role-arn> # Replace with your AWS IAM role ARN for Secrets Manager access
