apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: example-apicurio
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: example-apicurio
    app.kubernetes.io/managed-by: mint
    app.kubernetes.io/name: apicurio-registry
    app.kubernetes.io/part-of: apicurio-registry
    app.kubernetes.io/version: 3.0.9
  name: example-apicurio-app-ingress
  namespace: api-test
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - apicurio3-ui3.mint.revecore.com
      secretName: tls-secret
  rules:
  - host: apicurio3-ui3.mint.revecore.com
    http:
      paths:
      - backend:
          service:
            name: example-apicurio-app-service
            port:
              number: 8080
        path: /
        pathType: Prefix